[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_ACAD"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_ACAD"

[lid_events]

[scoring]
name_match = 10
description_match = 10
power_state_match = 3
lid_state_match = 2

[profiles.laptop_only]
config_file = '/home/nardi/.config/hyprdynamicmonitors/hyprconfigs/laptop.conf'
config_file_type = "template"
post_apply_exec = "hyprctl reload"
[profiles.laptop_only.conditions]
lid_state = "Opened"

[[profiles.laptop_only.conditions.required_monitors]]
name = "eDP-1"
monitor_tag = "laptop"

[profiles.MSI_attached]
config_file = "/home/nardi/.config/hyprdynamicmonitors/hyprconfigs/MSI_attached.conf"
config_file_type = "template"
post_apply_exec = "hyprctl reload"
[profiles.MSI_attached.conditions]

[[profiles.MSI_attached.conditions.required_monitors]]
name = "eDP-1"
monitor_tag = "laptop"

[[profiles.MSI_attached.conditions.required_monitors]]
description = "Microstep MSI MD272QXP PB1H823C00425"
monitor_tag = "MSI"

[fallback_profile]
config_file = "/home/nardi/.config/hyprdynamicmonitors/hyprconfigs/fallback.conf"
config_file_type = "static"
